### ISSUE TITLE
Feature request: emmylua_doc_cli - Allow skipping `index.md` and `mkdocs.yml`

### ISSUE THREAD

**Issue by ColinKennedy** [CppCXY/emmylua-analyzer-rust#36]
I'd like to continually re-generate lua -> md -> html using `emmylua_doc_cli` (lua -> md) and `mkdocs` (md -> html) as a GitHub workflow.

I have a working example which can be viewed here: https://github.com/ColinKennedy/nvim-best-practices-plugin-template/blob/af8b2e5ae9cb0681ca27973787487502156fe2c2/.github/workflows/documentation.yml#L44-L67

Currently, `emmylua_doc_cli` generates the `docs/index.md` and `mkdocs.yml` file every time it is run. It would be nice if the behavior could be changed (either by default or with an additional flag) so that, if the `docs/index.md` / `mkdocs.yml` file already exists, `emmylua_doc_cli` will leave them alone. But if the files don't exist they should be created.

Since `emmylua_doc_cli` always overrides `docs/index.md` and `mkdocs.yml` each time, I "save" them to a temporary path and "restore" them after `emmylua_doc_cli` is done.

## Current - What I am doing now
```yml
      - name: Save File index.md
        if: hashFiles('markdown/docs/index.md') != ''
        run: |
          temp_file=`mktemp`
          echo "index_temporary_path=$temp_file" >> $GITHUB_ENV
          cp markdown/docs/index.md $temp_file

      - name: Save File mkdocs.yml
        if: hashFiles('markdown/mkdocs.yml') != ''
        run: |
          temp_file=`mktemp`
          echo "mkdocs_temporary_path=$temp_file" >> $GITHUB_ENV
          cp markdown/mkdocs.yml $temp_file

      - name: Generate Mkdocs Files With emmylua_doc_cli
        run: emmylua_doc_cli --input lua/ --output markdown/

      - name: Restore index.md
        if: env.index_temporary_path != ''
        run: cp $index_temporary_path markdown/docs/index.md

      - name: Restore mkdocs.yml
        if: env.mkdocs_temporary_path != ''
        run: cp $mkdocs_temporary_path markdown/mkdocs.yml
```

## Proposed Solution
```yml
      - name: Generate Mkdocs Files With emmylua_doc_cli
        run: emmylua_doc_cli --input lua/ --output markdown/ --ignore-existing=docs/index.md,mkdocs.yml
```

`--ignore-existing=docs/index.md,mkdocs.yml` lets you specify relative paths to the files to "create if they don't exist but don't touch if they already exist"
